mqtt:
  host: 192.168.2.200
  port: 1883
  user: home
  password: '{FRIGATE_MQTT_PASSWORD}'

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m

objects:
  track:
    - person
    - cup
    - scissors
    - book
    - toothbrush

cameras:
  default:
    ffmpeg:
      input: rtsp://rtsp:8554/unicast
    height: 972
    width: 1296
    fps: 5
